### ISSUE TITLE
Need to use region based provisioning by default.

### ISSUE THREAD

**Issue by thedodd** [objectrocket/python-client#29]
### todo
- [ ] create a set of constants representing the regions that are available.
- [ ] create a set of constants representing the zones that are available.
- [ ] client should validate that the given zone is valid when provisioning according to zone.
- [ ] client should validate that the given region is valid when provisioning according to region.
- [ ] client should default to `use_region=True` when creating instances (this is a backwards incompatible change, but we are not `1.0` yet, so it is ok).
